### ISSUE TITLE
Apt cache not finding locales package 

### ISSUE THREAD

**Issue by Robert16296** [esteve/ros2_pepper#16]
When using  `prepare_requirements_ros1.sh` it fails to find the locales package from the ROS1 docker file. I think it is because it is using the apt-get cache like it is said in [http://lenguyenthedat.com/docker-cache/](url).

Changing the line 
`RUN apt-get install -y --no-install-recommends locales`
to 
`RUN apt-get update && apt-get install -y --no-install-recommends locales` 
solved it for me. I am not sure it is needed for every apt-get though.

**Comment by fmrico** [comment]
Hi @Robert16296 ,

The script, as is, is working perfectly for me, staring from a clean image. Actually there is a `apt-get update` in the previous line...

Best
