### ISSUE TITLE
Error running prepare_requirements_ros1.sh

### ISSUE THREAD

**Issue by mcaniot** [esteve/ros2_pepper#21]
I tried to compile ros 1 for Pepper and I had some issues. Indeed, in the first docker run, I had an error when the code tried to run the configure command :  
```It was created by python configure 2.7, which was generated by GNU Autoconf 2.69.  Invocation command line was :
$ ../configure --prefix=/home/nao/.ros-root/Python-2.7.13 --enable-shared --disable-ipv6 ac_cv_file__dev_ptmx=yes ac_cv_file__dev_ptc=no

configure:2845: checking build system type
configure:2859: result: x86_64-pc-linux-gnu
configure:2879: checking host system type
configure:2892: result: x86_64-pc-linux-gnu
configure:3007: checking for --enable-universalsdk
configure:3048: result: no
configure:3058: checking for --with-universal-archs
configure:3075: result: 32-bit
configure:3232: checking MACHDEP
configure:3424: result: linux2
configure:3433: checking EXTRAPLATDIR
configure:3448: result: 
configure:3469: checking for --without-gcc
configure:3513: result: no
configure:3516: checking for --with-icc
configure:3536: result: no
configure:3630: checking for gcc
configure:3660: result: no
configure:3723: checking for cc
configure:3770: result: no
configure:3826: checking for cl.exe
configure:3856: result: no
configure:3880: error: in `/home/nao/Python-2.7.13-src/build-host':
configure:3882: error: no acceptable C compiler found in $PATH
```
You can find all the config.log [here](https://github.com/esteve/ros2_pepper/files/2632850/config.log).

I didn't understand why you need to build for the host so I tried to move on by removing the first docker run and I get a new error with the second after the creation of the makefile: 
`bash: make: command not found`

I find out that a few command is not found by the bash (like make, wget or vcs) when I launched `./prepare_requirements_ros1.sh`. How can I fix that ?

**Comment by fmrico** [comment]
It is strange... In prepare_requirements_ros1.sh you build a docker image from docker/Dockerfile_ros1, that actually install everything to configure and build....

Did you obtained any error when building the docker image?

Best

**Comment by mcaniot** [comment]
Yes I had errors on the `apt-get install`. I had to remove all `apt-get install` of the file Dockerfile_ros1. When the docker tried to perform an apt-get install I had error like this one : 
```
RUN apt-get install -y --no-install-recommends locales
 ---> Running in db1d3acb34c4
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'locales' has no installation candidate
The command '/bin/sh -c apt-get install -y --no-install-recommends locales' returned a non-zero code: 100
```
Or 

```
RUN apt-get install -y --no-install-recommends lsb-release software-properties-common
 ---> Running in 3b9161746565
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package lsb-release
E: Unable to locate package software-properties-common
```

Moreover, all the packages are already installed on my laptop

**Comment by mcaniot** [comment]
Hi !
I finally fixed my issue by replacing in the Dockerfile_ros1 the apt key server by:
`RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
`
